// Liste étendue des régions proposées à la création d'un restaurant.
// Groupées par continent pour l'UX (<optgroup>).
// Chaque entrée mappe vers un fuseau horaire IANA officiel.

export type Timezone = { region: string; timezone: string; groupe: string };

export const TIMEZONES: Timezone[] = [
  // France métropolitaine + DOM-TOM
  { region: "France métropolitaine", timezone: "Europe/Paris", groupe: "France" },
  { region: "Guadeloupe", timezone: "America/Guadeloupe", groupe: "France" },
  { region: "Martinique", timezone: "America/Martinique", groupe: "France" },
  { region: "Guyane française", timezone: "America/Cayenne", groupe: "France" },
  { region: "La Réunion", timezone: "Indian/Reunion", groupe: "France" },
  { region: "Mayotte", timezone: "Indian/Mayotte", groupe: "France" },
  { region: "Saint-Pierre-et-Miquelon", timezone: "America/Miquelon", groupe: "France" },
  { region: "Saint-Martin", timezone: "America/Marigot", groupe: "France" },
  { region: "Saint-Barthélemy", timezone: "America/St_Barthelemy", groupe: "France" },
  { region: "Nouvelle-Calédonie", timezone: "Pacific/Noumea", groupe: "France" },
  { region: "Polynésie française (Tahiti)", timezone: "Pacific/Tahiti", groupe: "France" },
  { region: "Wallis-et-Futuna", timezone: "Pacific/Wallis", groupe: "France" },

  // Europe
  { region: "Belgique", timezone: "Europe/Brussels", groupe: "Europe" },
  { region: "Suisse", timezone: "Europe/Zurich", groupe: "Europe" },
  { region: "Luxembourg", timezone: "Europe/Luxembourg", groupe: "Europe" },
  { region: "Allemagne", timezone: "Europe/Berlin", groupe: "Europe" },
  { region: "Autriche", timezone: "Europe/Vienna", groupe: "Europe" },
  { region: "Espagne", timezone: "Europe/Madrid", groupe: "Europe" },
  { region: "Portugal", timezone: "Europe/Lisbon", groupe: "Europe" },
  { region: "Italie", timezone: "Europe/Rome", groupe: "Europe" },
  { region: "Royaume-Uni", timezone: "Europe/London", groupe: "Europe" },
  { region: "Irlande", timezone: "Europe/Dublin", groupe: "Europe" },
  { region: "Pays-Bas", timezone: "Europe/Amsterdam", groupe: "Europe" },
  { region: "Danemark", timezone: "Europe/Copenhagen", groupe: "Europe" },
  { region: "Suède", timezone: "Europe/Stockholm", groupe: "Europe" },
  { region: "Norvège", timezone: "Europe/Oslo", groupe: "Europe" },
  { region: "Finlande", timezone: "Europe/Helsinki", groupe: "Europe" },
  { region: "Pologne", timezone: "Europe/Warsaw", groupe: "Europe" },
  { region: "République tchèque", timezone: "Europe/Prague", groupe: "Europe" },
  { region: "Hongrie", timezone: "Europe/Budapest", groupe: "Europe" },
  { region: "Roumanie", timezone: "Europe/Bucharest", groupe: "Europe" },
  { region: "Bulgarie", timezone: "Europe/Sofia", groupe: "Europe" },
  { region: "Grèce", timezone: "Europe/Athens", groupe: "Europe" },
  { region: "Ukraine", timezone: "Europe/Kyiv", groupe: "Europe" },
  { region: "Russie (Moscou)", timezone: "Europe/Moscow", groupe: "Europe" },
  { region: "Turquie", timezone: "Europe/Istanbul", groupe: "Europe" },
  { region: "Islande", timezone: "Atlantic/Reykjavik", groupe: "Europe" },
  { region: "Monaco", timezone: "Europe/Monaco", groupe: "Europe" },
  { region: "Malte", timezone: "Europe/Malta", groupe: "Europe" },

  // Amérique du Nord
  { region: "Canada — Terre-Neuve", timezone: "America/St_Johns", groupe: "Amérique du Nord" },
  { region: "Canada — Halifax", timezone: "America/Halifax", groupe: "Amérique du Nord" },
  { region: "Canada — Québec / Ontario", timezone: "America/Toronto", groupe: "Amérique du Nord" },
  { region: "Canada — Winnipeg", timezone: "America/Winnipeg", groupe: "Amérique du Nord" },
  { region: "Canada — Alberta", timezone: "America/Edmonton", groupe: "Amérique du Nord" },
  { region: "Canada — Vancouver", timezone: "America/Vancouver", groupe: "Amérique du Nord" },
  { region: "États-Unis — Est", timezone: "America/New_York", groupe: "Amérique du Nord" },
  { region: "États-Unis — Centre", timezone: "America/Chicago", groupe: "Amérique du Nord" },
  { region: "États-Unis — Montagnes", timezone: "America/Denver", groupe: "Amérique du Nord" },
  { region: "États-Unis — Pacifique", timezone: "America/Los_Angeles", groupe: "Amérique du Nord" },
  { region: "États-Unis — Alaska", timezone: "America/Anchorage", groupe: "Amérique du Nord" },
  { region: "États-Unis — Hawaï", timezone: "Pacific/Honolulu", groupe: "Amérique du Nord" },
  { region: "Mexique", timezone: "America/Mexico_City", groupe: "Amérique du Nord" },

  // Amérique centrale et Caraïbes
  { region: "Cuba", timezone: "America/Havana", groupe: "Caraïbes / Amérique centrale" },
  { region: "Haïti", timezone: "America/Port-au-Prince", groupe: "Caraïbes / Amérique centrale" },
  { region: "République dominicaine", timezone: "America/Santo_Domingo", groupe: "Caraïbes / Amérique centrale" },
  { region: "Jamaïque", timezone: "America/Jamaica", groupe: "Caraïbes / Amérique centrale" },
  { region: "Bahamas", timezone: "America/Nassau", groupe: "Caraïbes / Amérique centrale" },
  { region: "Trinité-et-Tobago", timezone: "America/Port_of_Spain", groupe: "Caraïbes / Amérique centrale" },
  { region: "Panama", timezone: "America/Panama", groupe: "Caraïbes / Amérique centrale" },
  { region: "Costa Rica", timezone: "America/Costa_Rica", groupe: "Caraïbes / Amérique centrale" },
  { region: "Guatemala", timezone: "America/Guatemala", groupe: "Caraïbes / Amérique centrale" },
  { region: "Honduras", timezone: "America/Tegucigalpa", groupe: "Caraïbes / Amérique centrale" },
  { region: "Nicaragua", timezone: "America/Managua", groupe: "Caraïbes / Amérique centrale" },
  { region: "Salvador", timezone: "America/El_Salvador", groupe: "Caraïbes / Amérique centrale" },
  { region: "Belize", timezone: "America/Belize", groupe: "Caraïbes / Amérique centrale" },

  // Amérique du Sud
  { region: "Brésil — Brasília / São Paulo", timezone: "America/Sao_Paulo", groupe: "Amérique du Sud" },
  { region: "Brésil — Manaus", timezone: "America/Manaus", groupe: "Amérique du Sud" },
  { region: "Argentine", timezone: "America/Argentina/Buenos_Aires", groupe: "Amérique du Sud" },
  { region: "Chili", timezone: "America/Santiago", groupe: "Amérique du Sud" },
  { region: "Uruguay", timezone: "America/Montevideo", groupe: "Amérique du Sud" },
  { region: "Paraguay", timezone: "America/Asuncion", groupe: "Amérique du Sud" },
  { region: "Bolivie", timezone: "America/La_Paz", groupe: "Amérique du Sud" },
  { region: "Pérou", timezone: "America/Lima", groupe: "Amérique du Sud" },
  { region: "Équateur", timezone: "America/Guayaquil", groupe: "Amérique du Sud" },
  { region: "Colombie", timezone: "America/Bogota", groupe: "Amérique du Sud" },
  { region: "Venezuela", timezone: "America/Caracas", groupe: "Amérique du Sud" },

  // Afrique du Nord
  { region: "Maroc", timezone: "Africa/Casablanca", groupe: "Afrique du Nord" },
  { region: "Algérie", timezone: "Africa/Algiers", groupe: "Afrique du Nord" },
  { region: "Tunisie", timezone: "Africa/Tunis", groupe: "Afrique du Nord" },
  { region: "Libye", timezone: "Africa/Tripoli", groupe: "Afrique du Nord" },
  { region: "Égypte", timezone: "Africa/Cairo", groupe: "Afrique du Nord" },
  { region: "Soudan", timezone: "Africa/Khartoum", groupe: "Afrique du Nord" },

  // Afrique de l'Ouest et Centrale
  { region: "Sénégal", timezone: "Africa/Dakar", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Mauritanie", timezone: "Africa/Nouakchott", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Mali", timezone: "Africa/Bamako", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Burkina Faso", timezone: "Africa/Ouagadougou", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Niger", timezone: "Africa/Niamey", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Guinée", timezone: "Africa/Conakry", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Guinée-Bissau", timezone: "Africa/Bissau", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Sierra Leone", timezone: "Africa/Freetown", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Liberia", timezone: "Africa/Monrovia", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Côte d'Ivoire", timezone: "Africa/Abidjan", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Ghana", timezone: "Africa/Accra", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Togo", timezone: "Africa/Lome", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Bénin", timezone: "Africa/Porto-Novo", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Nigeria", timezone: "Africa/Lagos", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Cameroun", timezone: "Africa/Douala", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Gabon", timezone: "Africa/Libreville", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Congo — Brazzaville", timezone: "Africa/Brazzaville", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "RD Congo — Kinshasa", timezone: "Africa/Kinshasa", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "RD Congo — Lubumbashi", timezone: "Africa/Lubumbashi", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "République centrafricaine", timezone: "Africa/Bangui", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Tchad", timezone: "Africa/Ndjamena", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Guinée équatoriale", timezone: "Africa/Malabo", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "São Tomé-et-Príncipe", timezone: "Africa/Sao_Tome", groupe: "Afrique de l'Ouest / Centrale" },
  { region: "Cap-Vert", timezone: "Atlantic/Cape_Verde", groupe: "Afrique de l'Ouest / Centrale" },

  // Afrique de l'Est et Australe
  { region: "Éthiopie", timezone: "Africa/Addis_Ababa", groupe: "Afrique de l'Est / Australe" },
  { region: "Kenya", timezone: "Africa/Nairobi", groupe: "Afrique de l'Est / Australe" },
  { region: "Tanzanie", timezone: "Africa/Dar_es_Salaam", groupe: "Afrique de l'Est / Australe" },
  { region: "Ouganda", timezone: "Africa/Kampala", groupe: "Afrique de l'Est / Australe" },
  { region: "Rwanda", timezone: "Africa/Kigali", groupe: "Afrique de l'Est / Australe" },
  { region: "Burundi", timezone: "Africa/Bujumbura", groupe: "Afrique de l'Est / Australe" },
  { region: "Djibouti", timezone: "Africa/Djibouti", groupe: "Afrique de l'Est / Australe" },
  { region: "Somalie", timezone: "Africa/Mogadishu", groupe: "Afrique de l'Est / Australe" },
  { region: "Érythrée", timezone: "Africa/Asmara", groupe: "Afrique de l'Est / Australe" },
  { region: "Madagascar", timezone: "Indian/Antananarivo", groupe: "Afrique de l'Est / Australe" },
  { region: "Île Maurice", timezone: "Indian/Mauritius", groupe: "Afrique de l'Est / Australe" },
  { region: "Seychelles", timezone: "Indian/Mahe", groupe: "Afrique de l'Est / Australe" },
  { region: "Comores", timezone: "Indian/Comoro", groupe: "Afrique de l'Est / Australe" },
  { region: "Angola", timezone: "Africa/Luanda", groupe: "Afrique de l'Est / Australe" },
  { region: "Namibie", timezone: "Africa/Windhoek", groupe: "Afrique de l'Est / Australe" },
  { region: "Botswana", timezone: "Africa/Gaborone", groupe: "Afrique de l'Est / Australe" },
  { region: "Zimbabwe", timezone: "Africa/Harare", groupe: "Afrique de l'Est / Australe" },
  { region: "Zambie", timezone: "Africa/Lusaka", groupe: "Afrique de l'Est / Australe" },
  { region: "Malawi", timezone: "Africa/Blantyre", groupe: "Afrique de l'Est / Australe" },
  { region: "Mozambique", timezone: "Africa/Maputo", groupe: "Afrique de l'Est / Australe" },
  { region: "Afrique du Sud", timezone: "Africa/Johannesburg", groupe: "Afrique de l'Est / Australe" },
  { region: "Lesotho", timezone: "Africa/Maseru", groupe: "Afrique de l'Est / Australe" },
  { region: "Eswatini", timezone: "Africa/Mbabane", groupe: "Afrique de l'Est / Australe" },

  // Moyen-Orient
  { region: "Liban", timezone: "Asia/Beirut", groupe: "Moyen-Orient" },
  { region: "Syrie", timezone: "Asia/Damascus", groupe: "Moyen-Orient" },
  { region: "Israël", timezone: "Asia/Jerusalem", groupe: "Moyen-Orient" },
  { region: "Palestine", timezone: "Asia/Hebron", groupe: "Moyen-Orient" },
  { region: "Jordanie", timezone: "Asia/Amman", groupe: "Moyen-Orient" },
  { region: "Arabie saoudite", timezone: "Asia/Riyadh", groupe: "Moyen-Orient" },
  { region: "Émirats arabes unis", timezone: "Asia/Dubai", groupe: "Moyen-Orient" },
  { region: "Qatar", timezone: "Asia/Qatar", groupe: "Moyen-Orient" },
  { region: "Bahreïn", timezone: "Asia/Bahrain", groupe: "Moyen-Orient" },
  { region: "Koweït", timezone: "Asia/Kuwait", groupe: "Moyen-Orient" },
  { region: "Oman", timezone: "Asia/Muscat", groupe: "Moyen-Orient" },
  { region: "Yémen", timezone: "Asia/Aden", groupe: "Moyen-Orient" },
  { region: "Iran", timezone: "Asia/Tehran", groupe: "Moyen-Orient" },
  { region: "Irak", timezone: "Asia/Baghdad", groupe: "Moyen-Orient" },

  // Asie
  { region: "Inde", timezone: "Asia/Kolkata", groupe: "Asie" },
  { region: "Pakistan", timezone: "Asia/Karachi", groupe: "Asie" },
  { region: "Bangladesh", timezone: "Asia/Dhaka", groupe: "Asie" },
  { region: "Sri Lanka", timezone: "Asia/Colombo", groupe: "Asie" },
  { region: "Népal", timezone: "Asia/Kathmandu", groupe: "Asie" },
  { region: "Afghanistan", timezone: "Asia/Kabul", groupe: "Asie" },
  { region: "Chine", timezone: "Asia/Shanghai", groupe: "Asie" },
  { region: "Hong Kong", timezone: "Asia/Hong_Kong", groupe: "Asie" },
  { region: "Taïwan", timezone: "Asia/Taipei", groupe: "Asie" },
  { region: "Japon", timezone: "Asia/Tokyo", groupe: "Asie" },
  { region: "Corée du Sud", timezone: "Asia/Seoul", groupe: "Asie" },
  { region: "Mongolie", timezone: "Asia/Ulaanbaatar", groupe: "Asie" },
  { region: "Thaïlande", timezone: "Asia/Bangkok", groupe: "Asie" },
  { region: "Vietnam", timezone: "Asia/Ho_Chi_Minh", groupe: "Asie" },
  { region: "Cambodge", timezone: "Asia/Phnom_Penh", groupe: "Asie" },
  { region: "Laos", timezone: "Asia/Vientiane", groupe: "Asie" },
  { region: "Birmanie (Myanmar)", timezone: "Asia/Yangon", groupe: "Asie" },
  { region: "Malaisie", timezone: "Asia/Kuala_Lumpur", groupe: "Asie" },
  { region: "Singapour", timezone: "Asia/Singapore", groupe: "Asie" },
  { region: "Indonésie — Jakarta", timezone: "Asia/Jakarta", groupe: "Asie" },
  { region: "Philippines", timezone: "Asia/Manila", groupe: "Asie" },
  { region: "Kazakhstan", timezone: "Asia/Almaty", groupe: "Asie" },
  { region: "Ouzbékistan", timezone: "Asia/Tashkent", groupe: "Asie" },

  // Océanie
  { region: "Australie — Sydney", timezone: "Australia/Sydney", groupe: "Océanie" },
  { region: "Australie — Adélaïde", timezone: "Australia/Adelaide", groupe: "Océanie" },
  { region: "Australie — Perth", timezone: "Australia/Perth", groupe: "Océanie" },
  { region: "Australie — Brisbane", timezone: "Australia/Brisbane", groupe: "Océanie" },
  { region: "Nouvelle-Zélande", timezone: "Pacific/Auckland", groupe: "Océanie" },
  { region: "Fidji", timezone: "Pacific/Fiji", groupe: "Océanie" },
  { region: "Vanuatu", timezone: "Pacific/Efate", groupe: "Océanie" },
  { region: "Samoa", timezone: "Pacific/Apia", groupe: "Océanie" },
  { region: "Tonga", timezone: "Pacific/Tongatapu", groupe: "Océanie" },
  { region: "Papouasie-Nouvelle-Guinée", timezone: "Pacific/Port_Moresby", groupe: "Océanie" },
];

export function regionDe(timezone: string): string {
  return TIMEZONES.find((t) => t.timezone === timezone)?.region ?? timezone;
}

export const TIMEZONES_VALIDES = new Set(TIMEZONES.map((t) => t.timezone));

// Groupé pour <optgroup>
export const TIMEZONES_PAR_GROUPE = TIMEZONES.reduce((acc, t) => {
  (acc[t.groupe] ??= []).push(t);
  return acc;
}, {} as Record<string, Timezone[]>);
